// Generated by scripts/build-docs-nav.mjs. Do not edit manually.

import type { DefaultTheme } from 'vitepress'

export const sidebar: DefaultTheme.SidebarItem[] = 
[
  {
    "text": "Introduction",
    "link": "/"
  },
  {
    "text": "Install",
    "link": "/install"
  },
  {
    "text": "Usage",
    "link": "/usage",
    "items": [
      {
        "text": "Renderer entry with JSX",
        "link": "/usage#renderer-entry-with-jsx"
      },
      {
        "text": "Main entry",
        "link": "/usage#main-entry"
      }
    ],
    "collapsed": false
  },
  {
    "text": "License",
    "link": "/license"
  }
]
